spring:
  application:
    name: gateway-service
    version: @project.version@
  profiles:
    active: home
  webflux:
    base-path: "/home"

server:
  port: 6200

logbook:
  format:
    style: http

logging:
  level:
    org.zalando.logbook: trace

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 6001
management:
  server:
    port: 8001