spring:
  application:
    name: gateway-service
    version: @project.version@
  profiles:
    active: home
  webflux:
    base-path: "/home"

server:
  port: 6200

---

spring:
  profiles:
    active: local

server:
  port: 6001
management:
  server:
    port: 8001