name: CI

on:
  push:
    branches: [feature/**]
  pull_request:
    branches: [main]
    types: [ opened ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github-prv
          server-username: GH_PRV_USERNAME
          server-password: GH_PRV_PASSWORD

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Discord notification -> success
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "CI gateway-service - success"
      - name: Discord notification -> non-success
        uses: sarisia/actions-status-discord@v1
        if: ${{ !success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "CI gateway-service - failure"